version: "3"
services:
  app:
    build:
      context: .  # ✅ This tells Docker Compose to use the Dockerfile in the current directory
      dockerfile: Dockerfile  # ✅ Explicitly specifying Dockerfil
      args:  # ✅ Pass environment variables at build time
        - NEXT_PUBLIC_SANITY_DATASET=production
        - NEXT_PUBLIC_SANITY_PROJECT_ID=5kygfurw
    image: biopicta-website:latest  # ✅ Name of the built image
    container_name: biopicta-container
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.Biopicta.rule=Host(`biopicta.com`)"  # ✅ Quotes added
      - "traefik.http.routers.Biopicta.entrypoints=websecure"
      - "traefik.http.services.Biopicta.loadbalancer.server.port=8009"
      - "traefik.http.routers.Biopicta.tls=true"
      - "traefik.http.routers.Biopicta.tls.certresolver=myresolver"
    networks:
      - traefik

    environment:
      - NEXT_PUBLIC_SANITY_DATASET=production  # ✅ Add this
      - NEXT_PUBLIC_SANITY_PROJECT_ID=5kygfurw  # ✅ Add this


    command: ["npm", "start", "--", "-p", "8009"]  # ✅ Explicitly specify port

networks:
  traefik:
    external: true