name: Docker Image CI for GHCR

on: push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build and publish the image
        run: |
          docker login --username M-Mussab --password ${{secrets.GH_PAT}} ghcr.io
          docker build . --tag ghcr.io/M-Mussab/biopicta-ghcr:latest
          docker push ghcr.io/M-Mussab/biopicta-ghcr:latest